### ISSUE TITLE
Write final paper

### ISSUE THREAD

**Issue by jwnorm** [jwnorm/fantasy_draft#2]
Use the [project_proposal](https://github.com/jwnorm/fantasy_draft/blob/main/project_proposal-Norman.pdf) as a starting point. Most of the additional content will come from the analysis from [base.jl](https://github.com/jwnorm/fantasy_draft/blob/main/model/julia/base.jl) and [scenarios.jl](https://github.com/jwnorm/fantasy_draft/blob/main/model/julia/scenarios.jl).

**Comment by jwnorm** [comment]
**TODO:**
- [x] Add citations
- [x] Explain where targets and ADP are sourced from and why
- [x] Add mathematical changes to model in each scenario
- [x] Explain linear approximation of ratios
- [x] Add headers to tables
- [x] Expand appendix
- [x] Add conclusion
- [x] Add cover page
- [x] Add abstract
